application: itsthisforthat
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /.*
  script: thisforthat.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest